export const FILTER_POKEMONS = 'FILTER_POKEMONS'
export const FETCH_POKEMONS_SUCCESS = 'FETCH_POKEMONS_SUCCESS'
export const POKEMONS_FETCHING = 'POKEMONS_FETCHING'
export const FETCH_POKEMONS_FAILED = 'FETCH_POKEMONS_FAILED'
